import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { InternetCheck } from "@/utils";
import { Toaster } from "react-hot-toast";
import { Footer, Header } from "@/components";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: {
    template: "%s | Ruby",
    default: "Ruby",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className='debug-screens'>

        <Providers>

          <Suspense>

            <Header />

            {children}

            <Footer />

          </Suspense>

        </Providers>

        <InternetCheck />

        <Toaster
          position="top-center"
          reverseOrder={false}
        />

      </body>
    </html>
  );
}
